# Generated by Django 5.1.3 on 2024-12-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliostocks',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfoliostocks',
            name='portfolio_id',
            field=models.TextField(default='0'),
        ),
    ]
