# Generated by Django 5.1.3 on 2024-11-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('opening_price', models.FloatField()),
                ('highest_price', models.FloatField()),
                ('lowest_price', models.FloatField()),
                ('closing_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
