# Generated by Django 5.1.3 on 2024-11-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtests',
            fields=[
                ('backtest_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('total_return', models.FloatField(blank=True, null=True)),
                ('annualized_return', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Backtests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Portfolios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.TextField()),
                ('allocation', models.FloatField()),
            ],
            options={
                'db_table': 'Portfolio_Stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('google_id', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
