# Generated by Django 5.1.3 on 2024-12-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.IntegerField()),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("ticker", "date")},
            },
        ),
    ]
