# Generated by Django 5.1.3 on 2024-12-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockapp", "0002_stockhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backtests",
            options={"managed": True},
        ),
    ]
