# Generated by Django 5.1.3 on 2024-12-07 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockapp", "0003_alter_backtests_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio_Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.TextField()),
                ("allocation", models.FloatField()),
            ],
            options={
                "db_table": "Portfolio_Stocks",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="PortfolioStocks",
        ),
        migrations.AddField(
            model_name="backtests",
            name="initial_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtests",
            name="portfolio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stockapp.portfolios",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="backtests",
            name="rebalance_values",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtests",
            name="sharpe_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
